#!/usr/bin/env python3
"""Check one real run without synthesizing or labeling responsibility."""

from __future__ import annotations

import argparse
import json
import sqlite3
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[2]


def load_json_lines(path: Path) -> list[dict[str, Any]]:
    rows = []
    for line in path.read_text(encoding="utf-8", errors="replace").splitlines():
        try:
            value = json.loads(line)
        except json.JSONDecodeError:
            continue
        if isinstance(value, dict):
            rows.append(value)
    return rows


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("run_dir", type=Path, help="real run directory")
    parser.add_argument("--normalized", type=Path, required=True, help="normalized evidence-events.jsonl")
    parser.add_argument("--output", type=Path, help="optional report path")
    args = parser.parse_args()
    run_dir = args.run_dir.resolve()
    events = load_json_lines(args.normalized.resolve())
    app = [e for e in events if e.get("record_type") == "application.result"]
    sight = [e for e in events if str(e.get("record_type", "")).startswith("agentsight.")]
    observed_tools = [e.get("fields", {}).get("tool_name") for e in sight if e.get("record_type") == "agentsight.tool_calls"]
    db = run_dir / "session.db"
    counts: dict[str, int] = {}
    if db.exists():
        connection = sqlite3.connect(f"file:{db.as_posix()}?mode=ro", uri=True)
        tables = [x[0] for x in connection.execute("select name from sqlite_master where type='table'")]
        for table in tables:
            counts[table] = connection.execute(f"select count(*) from {table}").fetchone()[0]
        connection.close()
    costs = [e["cost_usd"] for e in app if isinstance(e.get("cost_usd"), (int, float))]
    report = {
        "schema_version": "trace-adapter-smoke-v0.1",
        "checked_at": datetime.now(timezone.utc).isoformat().replace("+00:00", "Z"),
        "run_id": run_dir.name,
        "real_api_evidence": {
            "application_result_records": len(app),
            "reported_cost_usd": sum(costs),
            "session_ids": sorted({e.get("session_id") for e in app if e.get("session_id")}),
            "agent_exit_codes": {
                p.name: p.read_text(encoding="utf-8", errors="replace").strip()
                for p in run_dir.glob("agent-*-exit.txt")
            },
        },
        "agentsight_evidence": {
            "sqlite_exists": db.exists(),
            "table_counts": counts,
            "normalized_records": len(sight),
            "observed_tool_names": observed_tools,
        },
        "task_evidence": {
            "route_exists": (run_dir / "workspace" / "route.json").exists() or (run_dir / "route.json").exists(),
            "decision_exists": (run_dir / "workspace" / "decision.json").exists() or (run_dir / "decision.json").exists(),
            "independent_ground_truth_exists": (run_dir / "ground_truth.json").exists(),
        },
        "chain_status": {
            "raw_observation_read": bool(sight),
            "application_log_read": len(app) >= 2,
            "task_artifacts_present": (run_dir / "workspace" / "decision.json").exists(),
            "unified_trace_ready": False,
            "responsibility_claim_made": False,
        },
        "remaining_gap": [
            "application logs are final-result records, not full step/tool JSONL",
            "cross-layer session/agent/step alignment is not implemented",
            "no responsibility label is generated by this smoke check",
        ],
    }
    output = args.output.resolve() if args.output else run_dir / "adapter-smoke-report.json"
    output.write_text(json.dumps(report, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(json.dumps(report, ensure_ascii=False, indent=2))
    return 0 if all(report["chain_status"].values()) else 0


if __name__ == "__main__":
    raise SystemExit(main())
