#!/usr/bin/env python3
"""Score a conservative trace-only attribution against a separate truth file."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


def load_trace(path: Path) -> list[dict]:
    return [json.loads(line) for line in path.read_text(encoding="utf-8").splitlines() if line.strip()]


def infer(trace: list[dict]) -> dict:
    final = next((x for x in trace if x.get("event_type") == "task.finish"), {})
    task = next((x for x in trace if x.get("event_type") == "task.start"), {})
    required = task.get("output_summary", {}).get("required_available")
    candidates = []
    for item in trace:
        if item.get("event_type") != "tool.result" or item.get("status") != "success":
            continue
        available = item.get("output_summary", {}).get("available")
        if required is not None and available is not None and available != required:
            candidates.append(item)
    if len(candidates) != 1:
        return {"prediction_status": "ambiguous", "candidate_event_ids": [x.get("event_id") for x in candidates]}
    tool_result = candidates[0]
    call = next((x for x in trace if x.get("event_id") == tool_result.get("parent_event_id")), {})
    call_index = next((i for i, x in enumerate(trace) if x.get("event_id") == call.get("event_id")), None)
    final_index = next((i for i, x in enumerate(trace) if x.get("event_type") == "task.finish"), None)
    interval_ids = []
    if call_index is not None and final_index is not None and call_index <= final_index:
        interval_ids = [x.get("event_id") for x in trace[call_index:final_index + 1]]
    return {
        "prediction_status": "single_candidate",
        "responsible_agent": tool_result.get("agent_id"),
        "responsible_step": call.get("step_id"),
        "responsible_edge": {"from_event_id": call.get("event_id"), "to_event_id": tool_result.get("event_id")},
        "candidate_event_ids": [tool_result.get("event_id")],
        "evidence_event_ids": interval_ids,
        "final_task_failed": final.get("status") == "failed",
    }


def compare(prediction: dict, truth: dict) -> dict:
    edge = prediction.get("responsible_edge")
    truth_edge = truth.get("responsible_edge")
    return {
        "agent_exact_match": prediction.get("responsible_agent") == truth.get("responsible_agent"),
        "step_exact_match": prediction.get("responsible_step") == truth.get("responsible_step"),
        "edge_exact_match": edge == truth_edge,
        "evidence_interval_recall": len(set(truth.get("evidence_event_ids", [])) & set(prediction.get("evidence_event_ids", []))) / max(1, len(truth.get("evidence_event_ids", []))),
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--run-dir", type=Path, required=True)
    parser.add_argument("--truth", type=Path, default=None, help="optional truth JSON path relative to run dir")
    parser.add_argument("--claim-status", default="VERIFIED_FOR_THIS_SYNTHETIC_PILOT")
    args = parser.parse_args()
    trace = load_trace(args.run_dir / "trace.jsonl")
    truth_path = args.truth or (args.run_dir / "ground_truth.json")
    if not truth_path.is_absolute():
        truth_path = args.run_dir / truth_path
    truth = json.loads(truth_path.read_text(encoding="utf-8"))
    prediction = infer(trace)
    scores = compare(prediction, truth)
    result = {
        "schema_version": "agentops-failure-analysis-v0.1",
        "run_id": truth.get("run_id"),
        "trace_event_count": len(trace),
        "prediction": prediction,
        "scores": scores,
        "baselines": {
            "B0_final_output_only": {"responsible_agent": None, "responsible_step": None, "status": "unidentifiable"},
            "B1_message_log_only": {"responsible_agent_candidates": ["agent_a", "agent_b"], "responsible_step": None, "status": "ambiguous"},
            "B2_tool_evidence": {"status": "scored_above"},
        },
        "interpretation": {
            "claim_status": args.claim_status,
            "limitations": ["single deterministic fault", "single two-agent workflow", "independent truth is generated by the same pilot harness", "no generalization or statistical significance"],
        },
    }
    (args.run_dir / "analysis.json").write_text(json.dumps(result, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(json.dumps(result, ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
